### ISSUE TITLE
[#1001] Tela de login

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#15]
## Descrição da atividade

Desenvolver interface para login no sistema conforme o [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias

chakra-ui, axios, react.

## Tela de Login

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/58437896/d8d73a49-01ae-42b2-a79d-faad3b82a644)

## Validações de credenciais

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/58437896/b3369693-a61a-460f-906c-878808270838)

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/58437896/bc67009f-0621-41a9-b700-d62d2dfb46fe)
