### ISSUE TITLE
[#0701] Busca por comentários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#2]
## Descrição da atividade

- Desenvolver interface para busca de comentarios, temas, ou sentimentos conforme o [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).

## Informações para execução da atividade

-  barra de pesquisa
- tabela de "últimos comentários"

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

React, chakra-ui, material-ui, styled-components.

## Resultados

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/1756d97d-ea08-4c2c-8f39-c13f76fe85c5)
