### ISSUE TITLE
[#0013] Refatoração: corrigir os code smells do frontend

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#20]
## Realizar a refatoração do maior número de code smells possíveis

É possível visualizar os code smells e suas informações na [análise realizada no sonarcloud](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=The-Bugger-Ducks_mood-hound-web&open=AYrKKkBRY8LeQv6kS274).

Atualmente temos **25 code smells** no frontend e deveremos evitar que esse número aumente nessa sprint.

**Comment by gioliveirass** [comment]
Documentação de alterações: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/38#issue-1929315712
