### ISSUE TITLE
[#0017] Refatoração: diminuir os botões da tela "cadastrar usuário"

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#21]

**Comment by gioliveirass** [comment]
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/27d9c36e-87e7-46fe-b0d7-9dd73a411938)

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O.
