### ISSUE TITLE
[#0018] Refatoração: diminuir o botão da tela "usuários do sistema"

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#22]

**Comment by gioliveirass** [comment]
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/c1d12647-ca28-409b-9434-12acb45b7d11)

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O.
