### ISSUE TITLE
[#0019] Refatoração: diminuir os botões da tela "atualizar minhas informações"

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#23]

**Comment by gioliveirass** [comment]
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/55b09d23-3466-46c8-a3d6-72cc9c23a10a)

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O.
