### ISSUE TITLE
[#0030] Refatoração: corrigir display dos comentários

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#27]
Atualmente os comentários mais longos não são mostrados completamente, tendo a partir do momento que excedem o limite de seu container reticências no final. O ideal é que o comentário seja mostrado completamente, então devemos adicionar um wrap a eles.

**Comment by gioliveirass** [comment]
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/4b4c39c3-37c4-455b-9844-af0a16d6264d)

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O.
