### ISSUE TITLE
[#0032] Refatoração: alterar nomenclatura dos usuários

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#28]
Atualmente os cargos de usuários que temos são **"admin"** e **"viewer"**, as nomenclaturas dos cargos devem ser modificadas para **"gestor"** e **"operador"**.

**Comment by gioliveirass** [comment]
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/4adcc245-9be4-4bcc-ba28-513557be0ebf)




![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/ef74b53c-417c-4b96-b5ff-7b76b0d1fe7c)



![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/2650cda7-d95d-46f8-83f1-326cf03526bc)



![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/167bb8f5-5c8b-49cd-b460-7d1b599000f5)

**Comment by drisabelles** [comment]
@GabrielCamargoL 

- [x] Aprovado pelo P.O.
