### ISSUE TITLE
[#0902] Cadastro de usuários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#3]
## Descrição da atividade

- Desenvolver interface para cadastro de usuários conforme o [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).
- Consumir rota para cadastro de usuários.

## Informações para execução da atividade

- Não precisa limitar a visualização por cargos por enquanto. 

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias

chakra-ui, axios, react.

## Tela de cadastro de usuários

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/f9cad4ab-6668-4deb-a0e4-eed4ccdc8d6a)

## Validações de senha

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/f1288a74-8efd-4c16-bc99-7aff504f2434)

![image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/4de4bc0d-c40a-4fac-a894-a72c5e23c357)
