### ISSUE TITLE
[#0402] Tabela de ranking dos 5 temas mais discutidos

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#32]
## Descrição da atividade

- Desenvolver interface com ranking de temas mais discutidos, conforme o [protótipo](https://whimsical.com/mood-hound-Jatkhh9Ypy6uHj3DuqoMXE).

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by drisabelles** [comment]
Aguardando o desenvolvimento do protótipo.
