### ISSUE TITLE
[#0502] Desenvolver gráfico de evolução dos temas

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#34]
## Descrição da atividade

- Desenvolver interface com evolução dos temas mais discutidos, conforme o [protótipo](https://whimsical.com/mood-hound-Jatkhh9Ypy6uHj3DuqoMXE).

## Informações para execução da atividade

- Evolução dos principais temas utilizando um gráfico de linha temporal vs parametro de satisfação [média de estrelas] (estrelas, por enquanto, devido ao algorítmo utilizado no pipeline de processamento)

- Utilize uma das opções ou se preferir, sugerir uma mais adequada: [Grafico Multilinha](https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/) ou [Zoomable Timeseries](https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by drisabelles** [comment]
Aguardando o desenvolvimento dos protótipos.
