### ISSUE TITLE
[#0501] Design evolução dos temas

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#35]
## Descrição da atividade

Desenvolver design no figma do projeto ilustrando gráficos de evolução dos temas tela da Dashboard (tela dos comentários).

## Informações para execução da atividade
- ~~ao clicar nos temas dessa [issue](https://github.com/orgs/The-Bugger-Ducks/projects/10/views/1?pane=issue&itemId=40115386)  renderizar os gráfico de evolução deste tema sobre a linha do tempo.~~
- Evolução dos principais temas utilizando um gráfico de linha temporal vs parametro de satisfação [média de estrelas] (estrelas, por enquanto, devido ao algorítmo utilizado no pipeline de processamento)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente

## DoD

- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

A idéia é centralizar qualquer interação com o dashboard na header, para não ficar muito confusa a utilização com o dashboard. Somente a tabela de últimas avalizações terá o filtro interno dela (que será mantido).

Talvez futuramente possamos implementar fitragem de range de data para alguns casos, mas nessa sprint provavelmente não dá mais tempo.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/b54387ef-57d6-4950-827f-01e28db2619e)

**Comment by drisabelles** [comment]
Protótipo de gráficos e suas disposições que foram acordados com o p.o: 
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/79321198/050c168d-0c1c-403b-acd8-eb00fb6d5f98)
