### ISSUE TITLE
[#0401] Design do Ranking de Temas

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#36]
## Descrição da atividade

Desenvolver design no figma do projeto ilustrando gráficos de Top 5 temas mais discutidos na tela da Dashboard (tela dos comentários).

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

A idéia é centralizar qualquer interação com o dashboard na header, para não ficar muito confusa a utilização com o dashboard. Somente a tabela de últimas avalizações terá o filtro interno dela (que será mantido).

Talvez futuramente possamos implementar fitragem de range de data para alguns casos, mas nessa sprint provavelmente não dá mais tempo.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/b54387ef-57d6-4950-827f-01e28db2619e)

**Comment by drisabelles** [comment]
Protótipo de gráficos e suas disposições que foram acordados com o p.o: 
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/79321198/050c168d-0c1c-403b-acd8-eb00fb6d5f98)
