### ISSUE TITLE
[#0903] CRUD de usuários no FIGMA

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#4]
## Descrição da atividade

- Prototipar formulário para cadastro e listagem de usuários, edição de cargo e remoção de contas no [figma](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).

## Informações para execução da atividade

- o formulario de cadastro precisa estar dentro do sistema, após o login. Apenas contas previamente criadas podem cadastrar novos usuários.
- um gestor deve ser capaz de listar usuários cadastrados
- um gestor deve ser capaz de mudar o cargo de outros usuários
- um gestor deve ser capaz de remover um usuário
- informações para cadastrar um usuário: nome, e-mail, senha e role 

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD
- [x] Prototipado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## 1️⃣ Listagem de usuário

Na aba "Informações do sistema", o usuário administrador poderá visualizar uma listagem de usuários cadastrados. A ideia é que, futuramente, novas informações sobre o sistema (como performance, etc.) sejam inseridas nessa mesma aba.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/d5a59c35-4aa4-45b3-be86-ea6b3a03a3d5)

O usuário poderá aplicar filtros na listagem de usuários cadastrados ao clicar no botão "Filtrar".

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/209db259-5eba-4297-94f1-c9d96250398e)

## 2️⃣ Remover usuário

O usuário administrador poderá remover um usuário ao selecionar a opção "Remover do sistema", na listagem de usuários cadastrados.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/b862a18e-8cff-4e50-acc1-76f3acca4e45)

## 3️⃣ Atualizar role (privilégio)

O usuário administrador poderá atualizar o privilégio do usuário ao selecionar a opção "Gerenciar privilégios", na listagem de usuários.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/586ea69d-5b44-4245-8f50-377ab9508863)

## 4️⃣ Cadastrar novo usuário

O usuário administrador poderá cadastrar um novo usuário ao selecionar a opção "Cadastrar novo usuário", na listagem de usuários. Ao selecionar o botão, ele será redirecionado para a seguinte página:

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/4391d39e-4b90-4d7f-8b53-12e33935a0b4)

Nessa página, também está disponível o botão de redefinir as informações novas inseridas no input.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/00ab92fd-43f6-48da-936c-627374c4a33b)

## 5️⃣ Edição de perfil

Cada usuário pode editar as informações do próprio perfil. Somente a informação de privilégios não pode ser editada, somente lida.

Para editar o perfil, o usuário pode selecionar o botão "Meu perfil" disponível em qualquer página.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/88230ba8-a9b6-40f3-9262-eb796e0d1521)

Na página de edição de perfil, também está disponível o botão de redefinir as informações novas inseridas no input.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/02730ac8-9560-4e4d-9f8e-2428ab187455)

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/099d379f-e47e-4828-b27c-7eb45dd42bca)
