### ISSUE TITLE
[#0904] Remoção de usuários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#5]
## Descrição da atividade

- Desenvolver ação de remover um usuário seguindo o [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).
- consumir rota para delete de usuários

## Informações para execução da atividade

- um gestor deve ser capaz de remover um usuário (não precisa se preocupar com autorização do cargo, por enquanto)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD
- [x] Code Review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

Chakra ui, axios, react

## Popup remove user

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/955e7545-12af-4c25-91f0-6ecd281fd7eb)

## Alerta de sucesso

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/d5025b31-53a1-432e-9a90-ef32f7c87461)
