### ISSUE TITLE
[#0406] Gráfico circular gauge

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#50]
## Descrição da atividade

Implementar o componente Circular Gauge para medir porcentagem de avaliações positivas.

_Exemplo:_

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/79321198/d4bde409-580b-4d01-8230-1d9b54696e8c)

## Informações para execução da atividade

- Executar essa tarefa após Prototipação concluida

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [ ] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

Gráfico circular gauge


![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/58437896/815314bd-f645-44dc-b5bd-1bdf3d0fb89e)
