### ISSUE TITLE
[#0412] Grafico de radar

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#53]
## Descrição da atividade

Implementar o componente Radar Chart para medir quantidade de avaliações entre os temas.

Seguir a idéia desse grafico:
![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/55204419/993a3652-cea5-4473-ac25-0d4754d6e854)
![Image](https://github.com/The-Bugger-Ducks/mood-hound-back/assets/55204419/866a69f7-266f-4fd5-baac-d139ba417f76)

## Informações para execução da atividade
Começar essa tarefa apos prototipação.

Componentes encontrados coo referencia de estrutura de dados:
[ApexCharts basic Radar Chart](https://apexcharts.com/react-chart-demos/radar-charts/basic/)
[Chart.js Radar](https://www.chartjs.org/docs/latest/samples/other-charts/radar.html)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [ ] Testado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

Gráfico de radar



![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/58437896/aef0d429-a36a-4118-9559-d6aff13c2167)
