### ISSUE TITLE
[#0905] Listagem de usuários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#6]
## Descrição da atividade

- Desenvolver interface para listagem de usuários conforme o [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).
- Consumir rota para listagem de usuários.

## Informações para execução da atividade

- Não precisa limitar a visualização por cargos por enquanto. 

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

MUI, Chakra-ui, react, yarn, react icons.

## Tabela de listagem de usuários

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/701ee806-ffb8-42a8-9e18-c4207ba1bc1f)


## Modal de pesquisa de usuários 

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/402362e5-6ada-43df-8604-28a60c8bcb12)
