### ISSUE TITLE
[#1603] Total de docs. processados e taxa de erros

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#66]
## Descrição da atividade

- Desenvolver exibição de total de documentos processados e exibição da taxa de erros do processamento destes documentos.

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
Documentação: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/71#issue-2005291188
