### ISSUE TITLE
[#1605] Gráfico de tempo de processamento total diário

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#67]
## Descrição da atividade

- Desenvolver exibição para um grafico temporal sobre o tempo em cada processamento, separado por dia.

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
Documentação: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/71#issue-2005291188
