### ISSUE TITLE
[#1607] Gráficos para exibição de erros

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#68]
## Descrição da atividade

- Desenvolver exibição sobre contagem de Erros Diários (Gráfico de barras) para visualizar a quantidade de erros por dia e 
- Desenolver tipos de Erro (Gráfico de pizza) para mostrar a distribuição percentual de diferentes tipos de erros.

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
Documentação: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/71#issue-2005291188
