### ISSUE TITLE
[#1609] Filtro de métricas por período

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#69]
## Descrição da atividade

- Desenvolver Filtros por Período: opção para escolher intervalos de tempo (data inicial e data final incluindo dia, mes e ano).

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
Documentação: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/71#issue-2005291188
