### ISSUE TITLE
[#0703] Integrar busca por comentários

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#7]
## Descrição da atividade

- Consumir rota responsável pela busca de comentários, temas e sentimento

## Informações para execução da atividade

- paginação;
- uso do react query

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

Axios, React, TypeScript, React Query, MuI, Chakra-ui.

## Listagem + Busca por comentário

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/b090a044-3ba9-4c0c-bbf0-6ec7d9e0863d)

## Filter

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/09884b5f-b637-4b7f-ae86-9112b04d3e9c)
