### ISSUE TITLE
[#1611] Gráfico de tempo em cada etapa do pipeline

### ISSUE THREAD

**Issue by GabrielCamargoL** [The-Bugger-Ducks/mood-hound-web#70]
## Descrição da atividade

- Desenvolver exibição para um grafico temporal (multi linha) sobre o tempo em cada etapa do processamento separado por dia.

## Informações para execução da atividade
Utilizar como base como referencia, a [demo no ApexCharts](https://apexcharts.com/react-chart-demos/line-charts/dashed/)

## DoR

- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Validado com o cliente
- [ ] Prototipado

## DoD

- [ ] Code review
- [ ] Testado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by gioliveirass** [comment]
Documentação: https://github.com/The-Bugger-Ducks/mood-hound-web/pull/71#issue-2005291188
