### ISSUE TITLE
[#0906] Edição de dados do usuário

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/mood-hound-web#9]
## Descrição da atividade

- Desenvolver funcionalidade de edição de usuários conforme o  [protótipo](https://www.figma.com/file/J89qcJeN5agiBMaGs2GCmc/Mood-Hound?type=design&node-id=0-1&mode=design&t=E2pQWLzQ7GbmQp96-0).
- Consumir rota para edição de usuários.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

React, chakra-ui, axios.

## Acesso ao meu perfil

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/2972b656-9951-485b-b2ed-3c57e19b3c93)


## Exibição de informação

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/9e02760f-ee01-4f73-8a8a-09f5249a3158)

## Alerta de redefinição de valor

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/fdb1d983-d966-4be8-ad35-6521d84a5eea)

## Mensagem de atualização

Ao atualizar um usuário, o usuário é redirecionado a Dashboard.

![Image](https://github.com/The-Bugger-Ducks/mood-hound-web/assets/78885451/6d3dae0b-ab49-4629-a686-6e3859954fe2)

**Comment by drisabelles** [comment]
@GabrielCamargoL falta só a aceitação do p.o
